PRODUTOS

In [229]:
produtos = [["Refrigerador A", 0.751, 999.90],["Celular", 0.0000899, 2199.12], ["TV 55'", 0.4, 4346.99], ["TV 50'", 0.29, 3999.90], ["TV 42'", 0.2, 2999.90], ['Notebook A', 0.0035, 2499.90], ['Ventilador', 0.496, 199.90], ["Microondas A", 0.0424, 308.66], ["Microondas B", 0.0544, 429.90], ["Microondas C", 0.0319, 299.29], ["Refrigerador B", 0.635, 849], ["Refrigerador C", 0.870, 1199.89], ["Notebook B", 0.498, 1999.90], ["Notebook C", 0.527, 3999]]

caminhao = []

FITNESS_FUNCTION

In [231]:
def fitness_function(selecao):
    id_produto = 0
    total_preco = 0
    total_espaco = 0
    for i in selecao:
        if i == 1:
            if total_espaco + produtos[id_produto][1] > 3:
                total_preco = 1
                return total_preco
            else:
                total_espaco += produtos[id_produto][1]
                total_preco += produtos[id_produto][2]
                caminhao.append(produtos[id_produto])
        id_produto += 1
    return total_preco


In [232]:
#EXECUÇÃO 

selecao = [0, 1, 0, 1 ,1, 0, 0, 1, 0, 0, 0, 1, 1, 1]

fitness_function(selecao)

16706.37

In [233]:
#IMPORT DOS PACOTES NECESSÁRIOS

import six
import sys
sys.modules['sklearn.externals.six'] = six
import mlrose

In [234]:
fitness = mlrose.CustomFitness(fitness_function)

In [235]:
problema = mlrose.DiscreteOpt(length=14,fitness_fn=fitness, maximize=True, max_val=2)

HILL CLIMB

In [249]:
#MELHOR SOLUÇÃO PELO ALGORITMO DE OTIMIZAÇÃO HILL CLIMB
melhor_solucao, melhor_preco = mlrose.hill_climb(problema)
melhor_solucao, melhor_preco

(array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1]), 18475.809999999998)

SIMULATED ANNEALING

In [237]:
#MELHOR SOLUÇÃO PELO ALGORITMO DE OTIMIZAÇÃO SIMULATED ANNEALING
melhor_solucao, melhor_preco = mlrose.simulated_annealing(problema)
melhor_solucao, melhor_preco

C:\Users\horac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mlrose\algorithms.py:311: RuntimeWarning: overflow encountered in exp
  prob = np.exp(delta_e/temp)


(array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1]), 23282.460000000003)

ALGORITMO GENÉTICO

In [238]:
#MELHOR SOLUÇÃO PELO ALGORITMO DE OTIMIZAÇÃO GENÉTICO
melhor_solucao, melhor_preco = mlrose.genetic_alg(problema)
melhor_solucao, melhor_preco

(array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1]), 24282.45)